### ISSUE TITLE
Sample cs-winui miss languages after it is published as a package

### ISSUE THREAD

**Issue by ilovepumpkin** [microsoft/WindowsAppSDK-Samples#156] opened 2022-01-12 10:39 UTC
Hello,
When I run the sample cs-winui ( https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/ResourceManagement/cs-winui) in Visual Studio (mine is VS 2019) - after clicking "Override Language" button, I can see the German text is displayed as expected.

![image](https://user-images.githubusercontent.com/11310645/149122314-4ab67a34-9dac-4a1d-93c0-5264751e3802.png)

However, after I publish it as a sideloading package and install it - right click on package project, select Publish > Create App Packages ... . 
![image](https://user-images.githubusercontent.com/11310645/149122810-d9cd77b3-6fce-4c1c-9c7d-a39128f54e45.png)

When I click "Override Language" button, it shows me the text in English.
![image](https://user-images.githubusercontent.com/11310645/149124885-7e896419-01ef-4d9b-86be-ef58c24c99c7.png)

It seems that resources in German is gone after packaging.  Is this a bug or any additional configuration is needed ? And if this is a known issue, is there any workaround I could apply?

**Comment by axelandrejs** [comment] 2022-01-26 00:23
Dupe of https://github.com/microsoft/WindowsAppSDK/issues/1980

**Closed by axelandrejs** 2022-01-26 00:23 UTC
Labels: area-resourcemanagement
