### ISSUE TITLE
Simple Island App crashes on quit

### ISSUE THREAD

**Issue by litherum** [microsoft/WindowsAppSDK-Samples#321] opened 2023-11-26 22:41 UTC
If you build and run the unmodified Simple Island App, and then quit the app, it crashes.

I'm not sure if this is helpful, but here is the stack trace: [Stack Trace.txt](https://github.com/microsoft/WindowsAppSDK-Samples/files/13468321/Stack.Trace.txt)

I'm using Windows 11 23H2, Windows 11 SDK 10.0.22000.0, Visual Studio 17.8.1, and Windows App SDK 1.4.3 (1.4.231115000).

**Comment by edward-a** [comment] 2024-01-31 09:18
Also wondering if there is a fix. From the call stack, it looks like it's caused by Visual Studio?

 	KernelBase.dll!RaiseFailFastException()	Unknown
 	Microsoft.UI.Input.dll!00007ffa58522a05()	Unknown
 	Microsoft.UI.Input.dll!00007ffa5856fa7d()	Unknown
 	Microsoft.UI.Input.dll!00007ffa5856fbc4()	Unknown
 	Microsoft.UI.Input.dll!00007ffa585568a5()	Unknown
 	Microsoft.UI.Input.dll!00007ffa58556275()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289007d9()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289319ef()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa28928687()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa28926d12()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289c15c9()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289d3727()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289ade9b()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffa289aa206()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2d8e4ed()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2d8e924()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2bcb63e()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2afbe7d()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2b6db02()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2b6dd8d()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2b6e18d()	Unknown
 	Microsoft.ui.xaml.dll!00007ff9c2b6e047()	Unknown
 	CoreMessagingXP.dll!00007ffa84e91378()	Unknown
 	CoreMessagingXP.dll!00007ffa84e91b3e()	Unknown
 	CoreMessagingXP.dll!00007ffa84e8ef5d()	Unknown
 	CoreMessagingXP.dll!00007ffa84e8ed3e()	Unknown
 	CoreMessagingXP.dll!00007ffa84e43bcc()	Unknown
 	CoreMessagingXP.dll!00007ffa84e3d8db()	Unknown
 	CoreMessagingXP.dll!00007ffa84e4750d()	Unknown
 	CoreMessagingXP.dll!00007ffa84e178ab()	Unknown
 	CoreMessagingXP.dll!00007ffa84e572a2()	Unknown
 	CoreMessagingXP.dll!00007ffa84e190d4()	Unknown
 	CoreMessagingXP.dll!00007ffa84e18963()	Unknown
 	CoreMessagingXP.dll!00007ffa84e0ed73()	Unknown
 	CoreMessagingXP.dll!00007ffa84e115ea()	Unknown
 	CoreMessagingXP.dll!00007ffa84e11aeb()	Unknown
 	CoreMessagingXP.dll!00007ffa84e119f4()	Unknown
 	CoreMessagingXP.dll!00007ffa84e4e56d()	Unknown
 	CoreMessagingXP.dll!00007ffa84e4e4f2()	Unknown
 	CoreMessagingXP.dll!00007ffa84e4e3a3()	Unknown
 	user32.dll!00007ffaf42c8241()	Unknown
 	user32.dll!00007ffaf42c7efc()	Unknown
 	user32.dll!00007ffaf42d302d()	Unknown
 	ntdll.dll!KiUserCallbackDispatcherContinue()	Unknown
 	win32u.dll!00007ffaf41914d4()	Unknown
 	user32.dll!00007ffaf42d1b4f()	Unknown
 	user32.dll!00007ffaf42d1a1c()	Unknown
 	CoreMessagingXP.dll!00007ffa84e4e9f4()	Unknown
 	CoreMessagingXP.dll!00007ffa84e11886()	Unknown
 	CoreMessagingXP.dll!00007ffa84e110d3()	Unknown
 	CoreMessagingXP.dll!00007ffa84e1a7a6()	Unknown
 	CoreMessagingXP.dll!00007ffa84e0eb79()	Unknown
 	CoreMessagingXP.dll!00007ffa84e145d0()	Unknown
 	CoreMessagingXP.dll!00007ffa84e8e783()	Unknown
 	CoreMessagingXP.dll!00007ffa84e88b5d()	Unknown
 	SimpleIslandApp.exe!winrt::impl::consume_Microsoft_UI_Dispatching_IDispatcherQueueController2<winrt::Microsoft::UI::Dispatching::DispatcherQueueController>::ShutdownQueue() Line 128	C++
>	SimpleIslandApp.exe!wWinMain(HINSTANCE__ *, HINSTANCE__ *, wchar_t *, int) Line 79	C++

**Comment by Scottj1s** [comment] 2024-07-31 20:55
This issue was fixed with Windows App SDK 1.5

**Closed by Scottj1s** 2024-07-31 20:55 UTC
